name: cobertura_dossel
description: "Aplicação mobile semiautomática para estimativa da cobertura aparente do dossel por imagens digitais."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  image_picker: ^1.2.2
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.7+1

flutter:
  uses-material-design: true
